### ISSUE TITLE
`Could not find a declaration file for module 'leaflet-area-select'.`

### ISSUE THREAD

**Issue by charlieforward9** [w8r/leaflet-area-select#41]
Add a new declaration (.d.ts) file containing `declare module 'leaflet-area-select';`

I might do this for ya.

**Comment by charlieforward9** [comment]
Something like this would be super ideal: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet-editable/index.d.ts

**Comment by charlieforward9** [comment]
I got something started based on Editable in my fork of the repo: https://github.com/charlieforward9/leaflet-area-select/blob/97dbd7f538b9c8961a7de5d71baa9438b85efd57/index.d.ts

**Comment by ivanmem** [comment]
How to import the file https://github.com/Agriculture-Intelligence/leaflet-area-select/blob/master/dist/index.d.ts?
After importing `import 'leaflet-area-select'` the type hints did not appear. For now I had to copy the file to myself.

**Comment by charlieforward9** [comment]
@ivanmem I think I had this problem too, if you figure out the fix, contribute that to the repo! Thanks.
