### ISSUE TITLE
Cannot read property '_simulated' of undefined using leaflet master version

### ISSUE THREAD

**Issue by cosme-benito** [w8r/leaflet-area-select#5]
I recently updated my leaflet version (1.0.0-rc.1+e2caf40) and it triggered a problem with this plugin. It was very easy to figure out the problem so I'll leave the solution here hoping that it will help others.

Line 300:

```
_onKeyPress: function(e) {
    if (this.options.ctrlKey && (e.ctrlKey || e.type === 'dragstart')
      && this._beforeCursor === null) {

      this._setCursor();
      this._map.dragging._draggable._onUp(); // hardcore
      this._map.dragging.disable();
    }
  },
```

The _onUp function apparenly now requires an event parameter so I just passed "e" to it and it seems to be working just fine.

`this._map.dragging._draggable._onUp(e); // hardcore`

I'm not sure this is the optimal solution but everything appears to be working fine.

**Comment by w8r** [comment]
just fixed it in the latest version, thanks!
